override:
  name: ""
  namespace: ""

scale:
  maxReplicaCount: 1
  replicaCount: 1

host: null

image:
  domain: null
  pullPolicy: IfNotPresent
  tag: ""

ingress:
  tls:
    secretName: ingress-tls

autoscaling:
  enabled: false

internal:
  port: 9441
  media: 8445

public:
  media: 28550
  ip: null

node:
  target: scale

terminationGracePeriod: 54000

container:
  env:
    azureSetting:
      captureEvents: false
      eventsFolder: events
      mediaFolder: archive
      eventhubKey: "5ZzUe5sG+afqx5PWlT2ZQm3rtbz7tc0+8dsHeXjkeqw="
      eventhubName: "vsalisrecordingbot"
      eventhubRegion: "northeurope"
      isStereo: false
      wavSampleRate: 0 # when it is 0, the default sample rate will be set per the stereo flag setting above
      wavQuality: 100      
  port: 9441

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
