name: 02_Initial_Setup_All_Infra

on:  
  workflow_run:
    workflows: ["01_Initial_Setup_Second_Step"]
    branches: [master]
    types: 
      - completed      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs: 
 Create_MiddleWare_And_AKS_Infra:    
    runs-on: ubuntu-latest
    env:
      BOT_ID: ${{secrets.BOT_ID}}
      BOT_SECRET: ${{secrets.BOT_SECRET}}
      SP_ID: ${{secrets.SP_ID}}
      SP_SECRET: ${{secrets.SP_SECRET}}
    steps:
    - uses: actions/checkout@v2
    - name: 'Load env variables from file using pwsh'
      shell: pwsh
      run: 03_IaC/00_AzureCLI/10_LoadEnvVariables.ps1
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true    
    - name: 'Run Setup Middleware powershell'
      shell: pwsh
      run: 03_IaC/00_AzureCLI/01_MiddleWare_iac.ps1
    - name: 'Run Setup AKS powershell'
      shell: pwsh
      run: 03_IaC/00_AzureCLI/02_AKS_iac.ps1